-- MySQL Script generated by MySQL Workbench
-- 02/04/17 10:03:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aspirantes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aspirantes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aspirantes` DEFAULT CHARACTER SET utf8 COLLATE utf8_latvian_ci ;
USE `aspirantes` ;

-- -----------------------------------------------------
-- Table `aspirantes`.`aspirante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`aspirante` (
  `CURP` NVARCHAR(18) NOT NULL,
  `nombre` NVARCHAR(50) NULL,
  `paterno` NVARCHAR(50) NULL,
  `materno` NVARCHAR(50) NULL,
  `preficha` NVARCHAR(8) NULL,
  `ficha` NVARCHAR(7) NULL,
  `fecha-pre` DATETIME NULL,
  `fecha_reg` DATETIME NULL,
  `correo` NVARCHAR(50) NULL,
  PRIMARY KEY (`CURP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspirantes`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`referencia` (
  `referenciasistema` NVARCHAR(20) NOT NULL,
  `fecha_generada` DATETIME NULL,
  `fecha_vigencia` DATE NULL,
  `monto` VARCHAR(10) NULL,
  `referenciabanco` NVARCHAR(20) NULL,
  `fecha_pago` DATE NULL,
  `tipo_pago` NVARCHAR(5) NULL,
  `fecha_registro` DATETIME NULL,
  `CURP` NVARCHAR(18) NOT NULL,
  PRIMARY KEY (`referenciasistema`, `CURP`),
  INDEX `fk_referencia_aspirante1_idx` (`CURP` ASC),
  CONSTRAINT `fk_referencia_aspirante1`
    FOREIGN KEY (`CURP`)
    REFERENCES `aspirantes`.`aspirante` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspirantes`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`grupo` (
  `clave` NVARCHAR(8) NOT NULL,
  `fecha_aplicacion` DATETIME NULL,
  `aula` NVARCHAR(50) NULL,
  `cupo` INT NULL,
  `estatus` NVARCHAR(1) NULL,
  PRIMARY KEY (`clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspirantes`.`aspirante_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`aspirante_grupo` (
  `grupo_clave` NVARCHAR(8) NOT NULL,
  `aspirante_CURP` NVARCHAR(18) NOT NULL,
  `registro` DATETIME NULL,
  PRIMARY KEY (`grupo_clave`, `aspirante_CURP`),
  INDEX `fk_aspirante_has_grupo_grupo1_idx` (`grupo_clave` ASC),
  INDEX `fk_aspirante_has_grupo_aspirante_idx` (`aspirante_CURP` ASC),
  CONSTRAINT `fk_aspirante_has_grupo_aspirante`
    FOREIGN KEY (`aspirante_CURP`)
    REFERENCES `aspirantes`.`aspirante` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aspirante_has_grupo_grupo1`
    FOREIGN KEY (`grupo_clave`)
    REFERENCES `aspirantes`.`grupo` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspirantes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` NVARCHAR(50) NULL,
  `pass` NVARCHAR(50) NULL,
  `tipo` NVARCHAR(1) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aspirantes`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aspirantes`.`acceso` (
  `clave` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`clave`, `usuario_id_usuario`),
  INDEX `fk_acceso_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_acceso_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `aspirantes`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
